apiVersion: apps/v1
metadata:
  name: postgres-pod
kind: Deployment
spec:
  template:
    metadata:
      name: post
      labels:
        appName: post-gres
    spec:
      containers:
        - name: postgress-app-container
          image: postgres:9.4
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "postgres"
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
          ports:
            - containerPort: 5432
  replicas: 1
  selector:
    matchLabels:
       appName: post-gres

